name: Your CSS code is valid
on: push
jobs:
  check-css-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check components.css existence
      uses: andstor/file-existence-action@v1
      with:
        files: "components.css"
        allow_failure: true

    - name: Check CSS
      uses: Cyb3r-Jak3/html5validator-action@v0.5
      with:
        root: .
        css: true
        log_level: DEBUG
